generator:
  class: sfPropelGenerator
  param:
    model_class:           sfEasyAuthUserBase
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_easy_auth_user
    with_propel_route:     1

    config:
      fields: 
        password:                   { label: New password }
        account_temporarily_locked: { label: Temporarily locked, type: boolean }
      list:
        sort: [ username, asc ]
        title:   User list
        display: [=username, type, created_at, last_login, locked_by_admins, account_temporarily_locked ]
      filter:  
        display: [ username, locked_by_admins, type ]
      form: ~
      edit:
        title: Editing User "%%username%%"

      new:
        title: New User
        display: [ username, password, enabled, type ]